### PR TITLE
update on st_as_sftime.cubble_df

### PR DESCRIPTION
**Pull request by huizezhang-sherry**
replace old syntax after internal refactoring in cubble

### CODE REVIEW

**Comment by edzer** [comment]
This breaks CI for this repo because cubble 0.3-0 is not yet on CRAN. When do you plan to submit it?

**Comment by huizezhang-sherry** [comment]
This week.

**Comment by huizezhang-sherry** [comment]
Cubble 0.3.0 is now on CRAN :)

**Comment by edzer** [comment]
Thanks! `stars` used to call `cubble::key_vars`. What should it do now that is no longer available? https://github.com/r-spatial/stars/blob/main/R/cubble.R#L34

**Comment by huizezhang-sherry** [comment]
You can use `head(names(attr(.x, "key")), -1)`. The generic of `key_vars` is in `tsibble`.

**Pull request merged**
